### ISSUE TITLE
Panic when parsing config defined functions with config defined variable args

### ISSUE THREAD

**Issue by Jeffail** [benhoyt/goawk#17]
When parsing a program using config defined functions, where an argument is a config defined variable, the parser panics with:

```
panic: runtime error: index out of range [recovered]
        panic: interface conversion: interface {} is runtime.errorString, not *parser.ParseError [recovered]                                
        panic: interface conversion: interface {} is runtime.errorString, not *parser.ParseError                                            

goroutine 321 [running]:
testing.tRunner.func1(0xc000179a00)
        /usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:792 +0x387                                                               
panic(0x118aea0, 0xc000386a50)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9                                                                 
github.com/benhoyt/goawk/parser.ParseProgram.func1(0xc00011fe08)
        /Users/ash/src/go/goawk/parser/parser.go:59 +0x98
panic(0x11895e0, 0x130d8f0)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9                                                                 
github.com/benhoyt/goawk/parser.(*parser).resolveVars(0xc000333180, 0xc000388310)                                                           
        /Users/ash/src/go/goawk/parser/resolve.go:260 +0x1caa
github.com/benhoyt/goawk/parser.(*parser).program(0xc000333180, 0xc000333180)                                                               
        /Users/ash/src/go/goawk/parser/parser.go:176 +0x8ca
github.com/benhoyt/goawk/parser.ParseProgram(0xc0000145a0, 0x16, 0x20, 0xc0000326e0, 0x0, 0x0, 0x0)                                         
        /Users/ash/src/go/goawk/parser/parser.go:71 +0x147
```

The panic is reproducible with this unit test:

``` go
func TestConfigVarsWithNativeFuncs(t *testing.T) {
	funcs := map[string]interface{}{
		"foo": func(i int) int {
			return i
		},
	}
	prog, err := parser.ParseProgram(
		[]byte(`BEGIN { print foo(x) }`), &parser.ParserConfig{
			Funcs: funcs,
		},
	)
	if err != nil {
		t.Fatalf("error parsing: %v", err)
	}

	outBuf := &bytes.Buffer{}
	errBuf := &bytes.Buffer{}
	config := &interp.Config{
		Stdin:  strings.NewReader(""),
		Output: outBuf,
		Error:  errBuf,
		Funcs:  funcs,
		Vars:   []string{"x", "5"},
	}
	if _, err = interp.ExecProgram(prog, config); err != nil {
		t.Fatal(err)
	}

	exp := "5\n"
	normalized := normalizeNewlines(outBuf.String() + errBuf.String())
	if normalized != exp {
		t.Fatalf("expected %q, got %q", exp, normalized)
	}
}
```

At a glance it looks as though it's because config defined functions aren't tracked the same way as others and this breaks the way in which variable type inference is done.

**Comment by Jeffail** [comment]
https://github.com/benhoyt/goawk/pull/18 is my attempt at simply burying my head in the sand by disabling the check for this particular occurrence.

**Comment by benhoyt** [comment]
Thanks @Jeffail -- good find, and great bug report. I think your fix is reasonable, but need to check a few things. You can go ahead with your patch in the meantime if you want, and I'll look at it further in the next few days.

Love your use of GoAWK in benthos! Is benthos a work project, or a side/hobby thing?

**Comment by Jeffail** [comment]
Sounds good, no rush. It started as a hobby but it's been a work project for a couple of years now. Thanks for building this, it's an awesome project and I imagine we're going to get a lot of use out of it via Benthos.

**Comment by Jeffail** [comment]
Awesome, thanks @benhoyt!
